name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1.3
        with:
          orion: "true"
          
      - name: Install device-compatible CydiaSubstrate
        run: |
          MS_DEB="mobilesubstrate_0.9.5012_iphoneos-arm.deb"
          curl -OL http://apt.saurik.com/debs/$MS_DEB

          # Extract .deb contents using ar and tar
          ar x $MS_DEB
          tar -xf data.tar.*

          # Make the Theos framework directory
          mkdir -p theos/vendor/lib/CydiaSubstrate.framework

          # Copy the actual binary (not a folder)
          cp Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate theos/vendor/lib/CydiaSubstrate.framework/

      - name: Build package (rootful)
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1 \
            VendettaTweak_LDFLAGS="-L$(pwd)/theos/vendor/lib/CydiaSubstrate.framework -lCydiaSubstrate"

      - name: Upload package (rootful)
        uses: actions/upload-artifact@v4
        with:
          name: "Package built by ${{ matrix.os }}"
          path: ${{ github.workspace }}/packages/*-arm.deb

      - name: Build rootless package
        run: |
          rm -f packages/*
          make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless \
            VendettaTweak_LDFLAGS="-L$(pwd)/theos/vendor/lib/CydiaSubstrate.framework -lCydiaSubstrate"

      - name: Upload rootless package
        uses: actions/upload-artifact@v4
        with:
          name: "Rootless package built by ${{ matrix.os }}"
          path: ${{ github.workspace }}/packages/*-arm64.deb
